#!/usr/bin/env bash
#shellcheck disable=SC1087,SC2155,SC2154,SC2025
##############################################################################%
#THEME_C1=155
#THEME_C2=112
#THEME_C3=22
#THEME_C4=249
#THEME_C5=99
#THEME_C6=55
C1="\[\033[${THEME_C1}m\]"
C2="\[\033[${THEME_C2}m\]"
C3="\[\033[${THEME_C3}m\]"
C4="\[\033[${THEME_C4}m\]"
C5="\[\033[${THEME_C5}m\]"
C6="\[\033[${THEME_C6}m\]"
CRESET="\[\033[0m\]"


show_repo_name() {
	local result="$(git rev-parse --show-toplevel 2> /dev/null)"
	echo -en "$(cat "$result"/.git/config | grep url | awk '{ print $3 }')"
}

show_repo() {
	if [[ -e $(git rev-parse --git-dir 2> /dev/null) ]]; then
		local result="$(git rev-parse --show-toplevel 2> /dev/null)"
		echo -en "$result"
	fi
}


PS1="\n"
PS1+="$C4"
PS1+="$(if [[ $SHLVL -gt 1 ]]; then echo -en "${C6}[${C5}${SHLVL}${C6}] "; fi)"
PS1+="$C1"
PS1+="$(date +%H:%M%p) "
PS1+="$C4"
PS1+="ts"
PS1+="$C2"
PS1+="@"
PS1+="$C3"
PS1+="\h "
PS1+="$C1"
PS1+="\w"
PS1+='$(if [[ -e $(git rev-parse --git-dir 2> /dev/null) ]]; then repo=$(show_repo_name); echo -en " \033[${THEME_C5};1m $(basename "${repo}") "; fi)'
PS1+="$CRESET"
PS1+="$C4"
PS1+='$(if [[ $? -gt 0 ]]; then echo -en "\[\033[38;5;196m\]"; fi)'
PS1+=" \$ "
PS1+="$CRESET"
