#!/usr/bin/env bash

# Cross-platform Aliases
################################################

# ls, file-ops and movement
if [ "$(command -v eza)" != '' ]; then
    EZA_OPTIONS=(
    	-F
    	--group-directories-first
    	-I='Library|Downloads|Desktop|Movies|Music|Pictures'
    	--no-time
		-s=name
		--color=always
		--no-icons
	)
    alias l='eza -TF -L=2 ${EZA_OPTIONS[@]}'
    alias ll='eza -aFlTh -L=2 ${EZA_OPTIONS[@]}' 
    alias lll='eza -aFlTh -L=4 ${EZA_OPTIONS[@]}'
    cdls() {
        cd "$@" || return;
        clear
        eza -F "${EZA_OPTIONS[@]}"
        echo
    }
else
    alias l='ls --color=always'
    alias la='ls -a --color=always'
    alias ll="ls -lhAF --color=always"
    cdls() {
      cd "$@" && ls -F --color=always
    }
fi
alias cd=cdls
alias rmr='trash -F '
alias cdbin='cd $EXEC_DIR'
alias lsbin='ls -lAhF --color=always $EXEC_DIR'

# git
alias gc='git clone'
alias ga="git add ."

# network and comms
alias ping='c; ping -c 5 '
alias p8="c; ping -c 5 8.8.8.8"
alias pubkey="pbcopy < ~/.ssh/id_rsa.pub && echo \"Public key copied to pasteboard.\""
alias fssh='fast-ssh'

# docker
alias dils='docker image ls'
alias dcls='docker container ls'
alias dpsa='docker ps -a'
alias dcup='docker compose -f ${DOCKER_FILE_DIR}/docker-compose.yml up -d'
alias dcdn='docker compose -f ${DOCKER_FILE_DIR}/docker-compose.yml stop'
alias dcpull='docker compose -f ${DOCKER_FILE_DIR}/docker-compose.yml pull'
alias dclogs='docker compose -f ${DOCKER_FILE_DIR}/docker-compose.yml logs -tf --tail=50'
alias dtail='docker logs -tf --tail=50'

# services managed by Homebrew
alias bls="brew services list"			# list all installed services
alias bstart="brew services start"		# start and enable service
alias bstop="brew services stop"		# stop and disable service
alias brst="brew services restart"		# reload service (pickup new config)
alias bsi="brew services info"			# show run/schedule status of service
 
# misc
alias ss="sudo "
alias c="clear"
alias edit='micro'

# macOS Aliases
set_macos_aliases() {
  alias kb='open ~/Downloads/kb_L0_4.png'
  alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
  alias nano="/opt/homebrew/bin/nano"
  alias tssh="/Applications/Tailscale.app/Contents/MacOS/Tailscale up --ssh"
  alias python="python3.11"
  alias kpc='keepassxc-cli '
}

[[ $(uname) == Darwin ]] &&  set_macos_aliases

