#!/usr/bin/env bash

# Env Vars for terminal and OS/FS structure
###########################################

## Cross-platform ##

# File System and references
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$HOME/.local/bin/run"
export EDITOR="micro"
export VISUAL="$EDITOR"
export SUDO_EDITOR="$EDITOR"
export SCRATCH_DIR="$HOME/.local/scratch"
export SECRETS_DIR="$HOME/.config/secrets"
export PKG_MANAGER="brew"
export PKG_MANAGER_PREFIX="/opt/homebrew"

# State controls
export HISTFILE="$XDG_STATE_HOME/.bash_history"   # History filepath
export HISTSIZE=100000                            # Maximum events for internal history
export SAVEHIST=100000                            # Maximum events in history file
export HISTFILESIZE=10000
export HISTCONTROL=ignoredups:ignorespace
export LESSHISTFILE="$HOME/CACHE/less/history"

# App Specific
export MICRO_CONFIG_HOME="$XDG_CONFIG_HOME/micro"
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export DOCKER_CLI_HINTS=false
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# Secrets
export SECRETSDIR="$XDG_CONFIG_HOME/secrets"
