#!/usr/bin/env bash
###############################################################################%
git config --global color.ui auto
git config --global user.email "tsharley@gmail.com"
git config --global user.name "tsharley"
