#!/usr/bin/env bash

declare -a paths

_pathstring=''

function _build_path() {

    paths_macos=( "/nix/var/nix/profiles/default/bin"
                         "${PKG_MANAGER_PREFIX}/sbin"
                          "${PKG_MANAGER_PREFIX}/bin"
                                "$HOME/.local/go/bin"
	                               "$HOME/.cargo/bin"
                                   "$HOME/.local/bin"
                                    "/usr/local/sbin"
                                     "/usr/local/bin"
                                          "/usr/sbin"
                                           "/usr/bin"
                                              "/sbin"
                                               "/bin" )

    paths_linux=( "$HOME/.local/bin"
                   "/usr/local/sbin"
                    "/usr/local/bin"
                         "/usr/sbin"
                          "/usr/bin"
                             "/sbin"
                              "/bin" )


    [ "${1}" == macos ] && paths=( "${paths_macos[@]}" )
    [ "${1}" == linux ] && paths=( "${paths_linux[@]}" )


    for d in "${paths[@]}"; do
        if [ "${_pathstring}" == '' ]; then
            _pathstring="${d}"
            continue
        else
            _pathstring="${_pathstring}:${d}"
        fi
    done

    export PATH="${_pathstring}"

}


if [ "$_OS" == macos ]; then
    _build_path macos
elif [ "$_OS" == linux ]; then
    _build_path linux
else
    echo "OS not supported"
fi
