#!/usr/bin/env bash
###############################################################################%

# Environment
PYTHONSTARTUP="$XDG_CONFIG_HOME/python3/pythonrc.py"
VIRTUALENVWRAPPER_PYTHON="$(which python3)"
WORKON_HOME="${HOME}/Envs"
PROJECT_HOME="${HOME}/Projects"
VIRTUALENVWRAPPER_PYTHON=/opt/homebrew/bin/python3
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_HOOK_DIR=$WORKON_HOME/.hooks
. "$(command -v virtualenvwrapper.sh)"

# Aliases
alias mkve='mkvirtualenv'
alias mktve='mktmpenv'
alias lsve='lsvirtualenv'
alias showve='showvirtualenv'
alias rmve='rmvirtualenv'
alias cpve='cpvirtualenv'
alias allve='allvirtualenv'
alias cdve='cdvirtualenv'
alias cdsite='cdsitepackages'
alias lssite='lssitepackages'
alias add2ve='add2virtualenv'
