#!/usr/bin/env bash

# shellcheck source=/dev/null
if [ "$(uname)" == Darwin ]; then
    #. ~/.config/gbt/gbt.conf tsm
    #PS1='\n$(gbt $?)'
    #PS1="\[$(tput setaf 34)\]\u\[$(tput setaf 34)\]@\[$(tput setaf 33)\]\h \[$(tput setaf 197)\]\w \[$(tput sgr0)\]$ "
    #export PS1="\[$(tput setaf 2)\]ts\[$(tput setaf 197)\]@\[$(tput setaf 33)\]m20 \[$(tput setaf 197)\]\W \[$(tput sgr0)\]$ "
    #export PS1='\[\e[38;5;22;1m\]\@ \u@\h \W \$ \[\e[0m\]'
    export PS1='\[\e[38;5;22;1m\]ts@m20 \W \$ \[\e[0m\]'
else
    PS1='\[\e[38;5;29;1;2m\]\u\[\e[0;1;38;5;33m\]@\[\e[38;5;29;2m\]\h \[\e[38;5;33;4m\]\w \[\e[24;38;5;29m\]\$ \[\e[0m\]'
fi
export PS1
