#!/usr/bin/env bash
# shellcheck source=/dev/null disable=SC2001

# virtualenv_prompt() {
#     [[ "$VIRTUAL_ENV" == "" ]] && return
#     local venv_name="${VIRTUAL_ENV##*/}"
#     if typeset -f deactivate >/dev/null; then
#         echo "[${venv_name}] "
#     else
#         echo "<${venv_name}> "
#     fi
#     VIRTUAL_ENV_DISABLE_PROMPT=1
#     PS1='$(virtualenv_prompt) \$ '
# }

# default theme, if not overridden by dolastrc (~/.local/init/*)
. mkPS1 -f 3 7
if [[ -n $SSH_CLIENT ]]; then PS1="$(echo "$PS1" | sed 's/@/- SSH -/g')"; fi


# added with ocaml installation
#if [ "${OCAML_ENV}" == true ]; then PS1='\[\e[38;5;220;1m\]\$ '; fi
