#!/usr/bin/env bash
# shellcheck source=/dev/null

_set_theme(){
	case "${1}" in
		maroon)
			PS1='\[\e[31;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		green)
			PS1='\[\e[32;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		olive)
			PS1='\[\e[33;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		navy)
			PS1='\[\e[34;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		purple)
			PS1='\[\e[35;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		teal)
			PS1='\[\e[36;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		silver)
			PS1='\[\e[37;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		gray)
			PS1='\[\e[90;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		red)
			PS1='\[\e[91;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		lime)
			PS1='\[\e[92;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		yellow)
			PS1='\[\e[93;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		blue)
			PS1='\[\e[94;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		fuchsia)
			PS1='\[\e[95;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		aqua)
			PS1='\[\e[96;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
		white)
			PS1='\[\e[97;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
	    	*)
	    	PS1='\[\e[97;1m\]\u@\h \W \$ \[\e[0m\]'
			;;
	esac
	export PS1
}

_set_theme "$@"
