#!/usr/bin/env bash
#shellcheck disable=SC2027,SC2046
##############################################################################%

_succeeded_() {
    echo -e "\033[38;2;5;205;5;1m${1}\033[0m"
}

_failed_() {
    echo -e "\033[38;2;250;3;3;1m${1}\033[0m"
}

_get_OS_() {
    local OS_ID=
    if [[ $(uname) == Darwin ]]; then
        OS_ID=macos
    else
        id_line=$(sudo cat /etc/os-release | grep ^ID=)
        OS_ID="${id_line/ID=/}"
    fi
    echo "$OS_ID"
    unset OS_ID
}


_install_for_Debian_() {
    if [[ ! $(docker compose version) ]]; then
        # Remove any existing artifacts
        for pkg in \
            docker.io docker-doc docker-compose \
            podman-docker containerd runc; do
            sudo apt-get remove $pkg
        done

        # Add Docker's official GPG key:
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/debian/gpg \
            -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
            "deb [arch=$(dpkg --print-architecture) \
            signed-by=/etc/apt/keyrings/docker.asc] \
            https://download.docker.com/linux/debian \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Update and install
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io \
            docker-buildx-plugin docker-compose-plugin
    fi
}

_install_for_Ubuntu_() {
    if [[ ! $(docker compose version) ]]; then
    	# Remove any existing artifacts
        for pkg in docker.io docker-doc docker-compose \
            docker-compose-v2 podman-docker containerd runc; do
    	    apt-get remove $pkg
    	done

        # Add Docker's official GPG key
    	apt-get update
    	apt-get install -y ca-certificates curl gnupg
    	install -m 0755 -d /etc/apt/keyrings
    	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
            gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    	chmod a+r /etc/apt/keyrings/docker.gpg

        # Add the repository to Apt sources
    	echo \
    	    "deb [arch="$(dpkg --print-architecture)" \
            signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu \
    	    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    	    tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Update and install
        apt-get update
    	apt-get install -y docker-ce docker-ce-cli containerd.io \
            docker-buildx-plugin docker-compose-plugin
    fi
}

_main_() {
    case "$(_get_OS_)" in
        debian)
            echo "Running Docker Install Script for Debian"
            _install_for_Debian_ && \
                _succeeded_ "Installation complete"
            ;;
        ubuntu)
            echo "Running Docker Install Script for Ubuntu"
            _install_for_Ubuntu_ && \
                _succeeded_ "Installation complete"
            ;;
        *)
            _failed_ "Unsupported OS. Exiting."
            exit 1
            ;;
    esac
}


_main_ "$@"
